# Generated by Django 4.1.5 on 2023-01-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_booking_reservation_slot_menu_menu_item_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booking_date",
            new_name="reservation_date",
        ),
    ]
